title: Services
fields:
  -
    handle: background_image
    field:
      max_files: 1
      mode: list
      container: images
      restrict: false
      allow_uploads: true
      show_filename: true
      show_set_alt: true
      type: assets
      display: 'Background Image'
      icon: assets
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
  -
    handle: services
    field:
      collapse: false
      previews: true
      fullscreen: true
      sets:
        new_set_group:
          display: 'New Set Group'
          instructions: null
          icon: null
          sets:
            service:
              display: Service
              instructions: null
              icon: null
              fields:
                -
                  handle: heading
                  field:
                    input_type: text
                    antlers: false
                    type: text
                    display: Heading
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                -
                  handle: image
                  field:
                    max_files: 1
                    mode: list
                    restrict: false
                    allow_uploads: true
                    show_filename: true
                    show_set_alt: true
                    type: assets
                    display: Image
                    icon: assets
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                    container: images
                -
                  handle: body
                  field:
                    antlers: false
                    type: textarea
                    display: Body
                    icon: textarea
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                -
                  handle: link
                  field:
                    type: link
                    display: Link
                    icon: link
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
      type: replicator
      display: Services
      icon: replicator
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
